export declare const useLordStore: import("pinia").StoreDefinition<"lord", import("pinia")._UnwrapAll<Pick<{
    dbPath: string;
    db: globalThis.Ref<{
        id: string;
        ip: string;
        username: string | null;
        computerName: string | undefined;
        defaultPrinter: {
            name: string;
            displayName: string;
            description: string;
            status: number;
            isDefault: boolean;
            options?: {
                copies?: string | undefined;
                'device-uri'?: string | undefined;
                finishings?: string | undefined;
                'job-cancel-after'?: number | undefined;
                'job-hold-until'?: string | undefined;
                'job-priority'?: number | undefined;
                'job-sheets'?: string | undefined;
                'marker-change-time'?: number | undefined;
                'number-up'?: number | undefined;
                'printer-commands'?: string | undefined;
                'printer-info'?: string | undefined;
                'printer-is-accepting-jobs'?: boolean | undefined;
                'printer-is-shared'?: boolean | undefined;
                'printer-is-temporary'?: boolean | undefined;
                'printer-location'?: string | undefined;
                'printer-make-and-model'?: string | undefined;
                'printer-state'?: number | undefined;
                'printer-state-change-time'?: number | undefined;
                'printer-state-reasons'?: string | undefined;
                'printer-type'?: number | undefined;
                'printer-uri-supported'?: string | undefined;
                system_driverinfo?: string | undefined;
            } | undefined;
        } | null;
        printers: {
            name: string;
            displayName: string;
            description: string;
            status: number;
            isDefault: boolean;
            options?: {
                copies?: string | undefined;
                'device-uri'?: string | undefined;
                finishings?: string | undefined;
                'job-cancel-after'?: number | undefined;
                'job-hold-until'?: string | undefined;
                'job-priority'?: number | undefined;
                'job-sheets'?: string | undefined;
                'marker-change-time'?: number | undefined;
                'number-up'?: number | undefined;
                'printer-commands'?: string | undefined;
                'printer-info'?: string | undefined;
                'printer-is-accepting-jobs'?: boolean | undefined;
                'printer-is-shared'?: boolean | undefined;
                'printer-is-temporary'?: boolean | undefined;
                'printer-location'?: string | undefined;
                'printer-make-and-model'?: string | undefined;
                'printer-state'?: number | undefined;
                'printer-state-change-time'?: number | undefined;
                'printer-state-reasons'?: string | undefined;
                'printer-type'?: number | undefined;
                'printer-uri-supported'?: string | undefined;
                system_driverinfo?: string | undefined;
            } | undefined;
        }[];
        toPrintsCommands: {
            originalName?: string | undefined;
            encoding: string;
            mimetype: string;
            destination: string;
            filename: string;
            path: string;
            size: number;
            printOptions?: {
                printer?: string | undefined;
                pages?: string | undefined;
                subset?: string | undefined;
                orientation?: string | undefined;
                scale?: string | undefined;
                monochrome?: boolean | undefined;
                side?: string | undefined;
                bin?: string | undefined;
                paperSize?: string | undefined;
                silent?: boolean | undefined;
                printDialog?: boolean | undefined;
                sumatraPdfPath?: string | undefined;
                copies?: number | undefined;
            } | null | undefined;
            addedBy?: (string | null) | undefined;
            addedTo?: (string | null) | undefined;
            isPrinted: boolean;
            addedTime: Date | number;
            printerName?: string | undefined;
        }[];
        trashes: {
            originalName?: string | undefined;
            encoding: string;
            mimetype: string;
            destination: string;
            filename: string;
            path: string;
            size: number;
            printOptions?: {
                printer?: string | undefined;
                pages?: string | undefined;
                subset?: string | undefined;
                orientation?: string | undefined;
                scale?: string | undefined;
                monochrome?: boolean | undefined;
                side?: string | undefined;
                bin?: string | undefined;
                paperSize?: string | undefined;
                silent?: boolean | undefined;
                printDialog?: boolean | undefined;
                sumatraPdfPath?: string | undefined;
                copies?: number | undefined;
            } | null | undefined;
            addedBy?: (string | null) | undefined;
            addedTo?: (string | null) | undefined;
            isPrinted: boolean;
            addedTime: Date | number;
            printerName?: string | undefined;
            trashedBy: string | null;
            trashedTime: Date | number | null;
            isDeleted: boolean;
            deletedBy?: (string | null) | undefined;
            deletedTime?: (Date | number | null) | undefined;
        }[];
        lastPrinted: Date | number;
        ConnectedPCs: {
            id?: string | undefined;
            ip: string;
            username?: (string | null) | undefined;
            computerName: string | undefined;
            lastSeen?: (Date | number) | undefined;
            lastPrinted?: (Date | number) | undefined;
            isConnected?: boolean | undefined;
            printers?: {
                name: string;
                displayName: string;
                description: string;
                status: number;
                isDefault: boolean;
                options?: {
                    copies?: string | undefined;
                    'device-uri'?: string | undefined;
                    finishings?: string | undefined;
                    'job-cancel-after'?: number | undefined;
                    'job-hold-until'?: string | undefined;
                    'job-priority'?: number | undefined;
                    'job-sheets'?: string | undefined;
                    'marker-change-time'?: number | undefined;
                    'number-up'?: number | undefined;
                    'printer-commands'?: string | undefined;
                    'printer-info'?: string | undefined;
                    'printer-is-accepting-jobs'?: boolean | undefined;
                    'printer-is-shared'?: boolean | undefined;
                    'printer-is-temporary'?: boolean | undefined;
                    'printer-location'?: string | undefined;
                    'printer-make-and-model'?: string | undefined;
                    'printer-state'?: number | undefined;
                    'printer-state-change-time'?: number | undefined;
                    'printer-state-reasons'?: string | undefined;
                    'printer-type'?: number | undefined;
                    'printer-uri-supported'?: string | undefined;
                    system_driverinfo?: string | undefined;
                } | undefined;
            }[] | undefined;
            printersDefault?: {
                name: string;
                displayName: string;
                description: string;
                status: number;
                isDefault: boolean;
                options?: {
                    copies?: string | undefined;
                    'device-uri'?: string | undefined;
                    finishings?: string | undefined;
                    'job-cancel-after'?: number | undefined;
                    'job-hold-until'?: string | undefined;
                    'job-priority'?: number | undefined;
                    'job-sheets'?: string | undefined;
                    'marker-change-time'?: number | undefined;
                    'number-up'?: number | undefined;
                    'printer-commands'?: string | undefined;
                    'printer-info'?: string | undefined;
                    'printer-is-accepting-jobs'?: boolean | undefined;
                    'printer-is-shared'?: boolean | undefined;
                    'printer-is-temporary'?: boolean | undefined;
                    'printer-location'?: string | undefined;
                    'printer-make-and-model'?: string | undefined;
                    'printer-state'?: number | undefined;
                    'printer-state-change-time'?: number | undefined;
                    'printer-state-reasons'?: string | undefined;
                    'printer-type'?: number | undefined;
                    'printer-uri-supported'?: string | undefined;
                    system_driverinfo?: string | undefined;
                } | undefined;
            } | undefined;
        }[];
        recentlyConnectedPCs: {
            id?: string | undefined;
            ip: string;
            username?: (string | null) | undefined;
            computerName: string | undefined;
            lastSeen?: (Date | number) | undefined;
            lastPrinted?: (Date | number) | undefined;
            isConnected?: boolean | undefined;
            printers?: {
                name: string;
                displayName: string;
                description: string;
                status: number;
                isDefault: boolean;
                options?: {
                    copies?: string | undefined;
                    'device-uri'?: string | undefined;
                    finishings?: string | undefined;
                    'job-cancel-after'?: number | undefined;
                    'job-hold-until'?: string | undefined;
                    'job-priority'?: number | undefined;
                    'job-sheets'?: string | undefined;
                    'marker-change-time'?: number | undefined;
                    'number-up'?: number | undefined;
                    'printer-commands'?: string | undefined;
                    'printer-info'?: string | undefined;
                    'printer-is-accepting-jobs'?: boolean | undefined;
                    'printer-is-shared'?: boolean | undefined;
                    'printer-is-temporary'?: boolean | undefined;
                    'printer-location'?: string | undefined;
                    'printer-make-and-model'?: string | undefined;
                    'printer-state'?: number | undefined;
                    'printer-state-change-time'?: number | undefined;
                    'printer-state-reasons'?: string | undefined;
                    'printer-type'?: number | undefined;
                    'printer-uri-supported'?: string | undefined;
                    system_driverinfo?: string | undefined;
                } | undefined;
            }[] | undefined;
            printersDefault?: {
                name: string;
                displayName: string;
                description: string;
                status: number;
                isDefault: boolean;
                options?: {
                    copies?: string | undefined;
                    'device-uri'?: string | undefined;
                    finishings?: string | undefined;
                    'job-cancel-after'?: number | undefined;
                    'job-hold-until'?: string | undefined;
                    'job-priority'?: number | undefined;
                    'job-sheets'?: string | undefined;
                    'marker-change-time'?: number | undefined;
                    'number-up'?: number | undefined;
                    'printer-commands'?: string | undefined;
                    'printer-info'?: string | undefined;
                    'printer-is-accepting-jobs'?: boolean | undefined;
                    'printer-is-shared'?: boolean | undefined;
                    'printer-is-temporary'?: boolean | undefined;
                    'printer-location'?: string | undefined;
                    'printer-make-and-model'?: string | undefined;
                    'printer-state'?: number | undefined;
                    'printer-state-change-time'?: number | undefined;
                    'printer-state-reasons'?: string | undefined;
                    'printer-type'?: number | undefined;
                    'printer-uri-supported'?: string | undefined;
                    system_driverinfo?: string | undefined;
                } | undefined;
            } | undefined;
        }[];
        lastCheckConnectedPC: Date | number;
        offlineComputers: {
            id?: string | undefined;
            ip: string;
            username?: (string | null) | undefined;
            computerName: string | undefined;
            lastSeen?: (Date | number) | undefined;
            lastPrinted?: (Date | number) | undefined;
            isConnected?: boolean | undefined;
            printers?: {
                name: string;
                displayName: string;
                description: string;
                status: number;
                isDefault: boolean;
                options?: {
                    copies?: string | undefined;
                    'device-uri'?: string | undefined;
                    finishings?: string | undefined;
                    'job-cancel-after'?: number | undefined;
                    'job-hold-until'?: string | undefined;
                    'job-priority'?: number | undefined;
                    'job-sheets'?: string | undefined;
                    'marker-change-time'?: number | undefined;
                    'number-up'?: number | undefined;
                    'printer-commands'?: string | undefined;
                    'printer-info'?: string | undefined;
                    'printer-is-accepting-jobs'?: boolean | undefined;
                    'printer-is-shared'?: boolean | undefined;
                    'printer-is-temporary'?: boolean | undefined;
                    'printer-location'?: string | undefined;
                    'printer-make-and-model'?: string | undefined;
                    'printer-state'?: number | undefined;
                    'printer-state-change-time'?: number | undefined;
                    'printer-state-reasons'?: string | undefined;
                    'printer-type'?: number | undefined;
                    'printer-uri-supported'?: string | undefined;
                    system_driverinfo?: string | undefined;
                } | undefined;
            }[] | undefined;
            printersDefault?: {
                name: string;
                displayName: string;
                description: string;
                status: number;
                isDefault: boolean;
                options?: {
                    copies?: string | undefined;
                    'device-uri'?: string | undefined;
                    finishings?: string | undefined;
                    'job-cancel-after'?: number | undefined;
                    'job-hold-until'?: string | undefined;
                    'job-priority'?: number | undefined;
                    'job-sheets'?: string | undefined;
                    'marker-change-time'?: number | undefined;
                    'number-up'?: number | undefined;
                    'printer-commands'?: string | undefined;
                    'printer-info'?: string | undefined;
                    'printer-is-accepting-jobs'?: boolean | undefined;
                    'printer-is-shared'?: boolean | undefined;
                    'printer-is-temporary'?: boolean | undefined;
                    'printer-location'?: string | undefined;
                    'printer-make-and-model'?: string | undefined;
                    'printer-state'?: number | undefined;
                    'printer-state-change-time'?: number | undefined;
                    'printer-state-reasons'?: string | undefined;
                    'printer-type'?: number | undefined;
                    'printer-uri-supported'?: string | undefined;
                    system_driverinfo?: string | undefined;
                } | undefined;
            } | undefined;
        }[];
    }, import("../declarations/LordStore").lordData | {
        id: string;
        ip: string;
        username: string | null;
        computerName: string | undefined;
        defaultPrinter: {
            name: string;
            displayName: string;
            description: string;
            status: number;
            isDefault: boolean;
            options?: {
                copies?: string | undefined;
                'device-uri'?: string | undefined;
                finishings?: string | undefined;
                'job-cancel-after'?: number | undefined;
                'job-hold-until'?: string | undefined;
                'job-priority'?: number | undefined;
                'job-sheets'?: string | undefined;
                'marker-change-time'?: number | undefined;
                'number-up'?: number | undefined;
                'printer-commands'?: string | undefined;
                'printer-info'?: string | undefined;
                'printer-is-accepting-jobs'?: boolean | undefined;
                'printer-is-shared'?: boolean | undefined;
                'printer-is-temporary'?: boolean | undefined;
                'printer-location'?: string | undefined;
                'printer-make-and-model'?: string | undefined;
                'printer-state'?: number | undefined;
                'printer-state-change-time'?: number | undefined;
                'printer-state-reasons'?: string | undefined;
                'printer-type'?: number | undefined;
                'printer-uri-supported'?: string | undefined;
                system_driverinfo?: string | undefined;
            } | undefined;
        } | null;
        printers: {
            name: string;
            displayName: string;
            description: string;
            status: number;
            isDefault: boolean;
            options?: {
                copies?: string | undefined;
                'device-uri'?: string | undefined;
                finishings?: string | undefined;
                'job-cancel-after'?: number | undefined;
                'job-hold-until'?: string | undefined;
                'job-priority'?: number | undefined;
                'job-sheets'?: string | undefined;
                'marker-change-time'?: number | undefined;
                'number-up'?: number | undefined;
                'printer-commands'?: string | undefined;
                'printer-info'?: string | undefined;
                'printer-is-accepting-jobs'?: boolean | undefined;
                'printer-is-shared'?: boolean | undefined;
                'printer-is-temporary'?: boolean | undefined;
                'printer-location'?: string | undefined;
                'printer-make-and-model'?: string | undefined;
                'printer-state'?: number | undefined;
                'printer-state-change-time'?: number | undefined;
                'printer-state-reasons'?: string | undefined;
                'printer-type'?: number | undefined;
                'printer-uri-supported'?: string | undefined;
                system_driverinfo?: string | undefined;
            } | undefined;
        }[];
        toPrintsCommands: {
            originalName?: string | undefined;
            encoding: string;
            mimetype: string;
            destination: string;
            filename: string;
            path: string;
            size: number;
            printOptions?: {
                printer?: string | undefined;
                pages?: string | undefined;
                subset?: string | undefined;
                orientation?: string | undefined;
                scale?: string | undefined;
                monochrome?: boolean | undefined;
                side?: string | undefined;
                bin?: string | undefined;
                paperSize?: string | undefined;
                silent?: boolean | undefined;
                printDialog?: boolean | undefined;
                sumatraPdfPath?: string | undefined;
                copies?: number | undefined;
            } | null | undefined;
            addedBy?: (string | null) | undefined;
            addedTo?: (string | null) | undefined;
            isPrinted: boolean;
            addedTime: Date | number;
            printerName?: string | undefined;
        }[];
        trashes: {
            originalName?: string | undefined;
            encoding: string;
            mimetype: string;
            destination: string;
            filename: string;
            path: string;
            size: number;
            printOptions?: {
                printer?: string | undefined;
                pages?: string | undefined;
                subset?: string | undefined;
                orientation?: string | undefined;
                scale?: string | undefined;
                monochrome?: boolean | undefined;
                side?: string | undefined;
                bin?: string | undefined;
                paperSize?: string | undefined;
                silent?: boolean | undefined;
                printDialog?: boolean | undefined;
                sumatraPdfPath?: string | undefined;
                copies?: number | undefined;
            } | null | undefined;
            addedBy?: (string | null) | undefined;
            addedTo?: (string | null) | undefined;
            isPrinted: boolean;
            addedTime: Date | number;
            printerName?: string | undefined;
            trashedBy: string | null;
            trashedTime: Date | number | null;
            isDeleted: boolean;
            deletedBy?: (string | null) | undefined;
            deletedTime?: (Date | number | null) | undefined;
        }[];
        lastPrinted: Date | number;
        ConnectedPCs: {
            id?: string | undefined;
            ip: string;
            username?: (string | null) | undefined;
            computerName: string | undefined;
            lastSeen?: (Date | number) | undefined;
            lastPrinted?: (Date | number) | undefined;
            isConnected?: boolean | undefined;
            printers?: {
                name: string;
                displayName: string;
                description: string;
                status: number;
                isDefault: boolean;
                options?: {
                    copies?: string | undefined;
                    'device-uri'?: string | undefined;
                    finishings?: string | undefined;
                    'job-cancel-after'?: number | undefined;
                    'job-hold-until'?: string | undefined;
                    'job-priority'?: number | undefined;
                    'job-sheets'?: string | undefined;
                    'marker-change-time'?: number | undefined;
                    'number-up'?: number | undefined;
                    'printer-commands'?: string | undefined;
                    'printer-info'?: string | undefined;
                    'printer-is-accepting-jobs'?: boolean | undefined;
                    'printer-is-shared'?: boolean | undefined;
                    'printer-is-temporary'?: boolean | undefined;
                    'printer-location'?: string | undefined;
                    'printer-make-and-model'?: string | undefined;
                    'printer-state'?: number | undefined;
                    'printer-state-change-time'?: number | undefined;
                    'printer-state-reasons'?: string | undefined;
                    'printer-type'?: number | undefined;
                    'printer-uri-supported'?: string | undefined;
                    system_driverinfo?: string | undefined;
                } | undefined;
            }[] | undefined;
            printersDefault?: {
                name: string;
                displayName: string;
                description: string;
                status: number;
                isDefault: boolean;
                options?: {
                    copies?: string | undefined;
                    'device-uri'?: string | undefined;
                    finishings?: string | undefined;
                    'job-cancel-after'?: number | undefined;
                    'job-hold-until'?: string | undefined;
                    'job-priority'?: number | undefined;
                    'job-sheets'?: string | undefined;
                    'marker-change-time'?: number | undefined;
                    'number-up'?: number | undefined;
                    'printer-commands'?: string | undefined;
                    'printer-info'?: string | undefined;
                    'printer-is-accepting-jobs'?: boolean | undefined;
                    'printer-is-shared'?: boolean | undefined;
                    'printer-is-temporary'?: boolean | undefined;
                    'printer-location'?: string | undefined;
                    'printer-make-and-model'?: string | undefined;
                    'printer-state'?: number | undefined;
                    'printer-state-change-time'?: number | undefined;
                    'printer-state-reasons'?: string | undefined;
                    'printer-type'?: number | undefined;
                    'printer-uri-supported'?: string | undefined;
                    system_driverinfo?: string | undefined;
                } | undefined;
            } | undefined;
        }[];
        recentlyConnectedPCs: {
            id?: string | undefined;
            ip: string;
            username?: (string | null) | undefined;
            computerName: string | undefined;
            lastSeen?: (Date | number) | undefined;
            lastPrinted?: (Date | number) | undefined;
            isConnected?: boolean | undefined;
            printers?: {
                name: string;
                displayName: string;
                description: string;
                status: number;
                isDefault: boolean;
                options?: {
                    copies?: string | undefined;
                    'device-uri'?: string | undefined;
                    finishings?: string | undefined;
                    'job-cancel-after'?: number | undefined;
                    'job-hold-until'?: string | undefined;
                    'job-priority'?: number | undefined;
                    'job-sheets'?: string | undefined;
                    'marker-change-time'?: number | undefined;
                    'number-up'?: number | undefined;
                    'printer-commands'?: string | undefined;
                    'printer-info'?: string | undefined;
                    'printer-is-accepting-jobs'?: boolean | undefined;
                    'printer-is-shared'?: boolean | undefined;
                    'printer-is-temporary'?: boolean | undefined;
                    'printer-location'?: string | undefined;
                    'printer-make-and-model'?: string | undefined;
                    'printer-state'?: number | undefined;
                    'printer-state-change-time'?: number | undefined;
                    'printer-state-reasons'?: string | undefined;
                    'printer-type'?: number | undefined;
                    'printer-uri-supported'?: string | undefined;
                    system_driverinfo?: string | undefined;
                } | undefined;
            }[] | undefined;
            printersDefault?: {
                name: string;
                displayName: string;
                description: string;
                status: number;
                isDefault: boolean;
                options?: {
                    copies?: string | undefined;
                    'device-uri'?: string | undefined;
                    finishings?: string | undefined;
                    'job-cancel-after'?: number | undefined;
                    'job-hold-until'?: string | undefined;
                    'job-priority'?: number | undefined;
                    'job-sheets'?: string | undefined;
                    'marker-change-time'?: number | undefined;
                    'number-up'?: number | undefined;
                    'printer-commands'?: string | undefined;
                    'printer-info'?: string | undefined;
                    'printer-is-accepting-jobs'?: boolean | undefined;
                    'printer-is-shared'?: boolean | undefined;
                    'printer-is-temporary'?: boolean | undefined;
                    'printer-location'?: string | undefined;
                    'printer-make-and-model'?: string | undefined;
                    'printer-state'?: number | undefined;
                    'printer-state-change-time'?: number | undefined;
                    'printer-state-reasons'?: string | undefined;
                    'printer-type'?: number | undefined;
                    'printer-uri-supported'?: string | undefined;
                    system_driverinfo?: string | undefined;
                } | undefined;
            } | undefined;
        }[];
        lastCheckConnectedPC: Date | number;
        offlineComputers: {
            id?: string | undefined;
            ip: string;
            username?: (string | null) | undefined;
            computerName: string | undefined;
            lastSeen?: (Date | number) | undefined;
            lastPrinted?: (Date | number) | undefined;
            isConnected?: boolean | undefined;
            printers?: {
                name: string;
                displayName: string;
                description: string;
                status: number;
                isDefault: boolean;
                options?: {
                    copies?: string | undefined;
                    'device-uri'?: string | undefined;
                    finishings?: string | undefined;
                    'job-cancel-after'?: number | undefined;
                    'job-hold-until'?: string | undefined;
                    'job-priority'?: number | undefined;
                    'job-sheets'?: string | undefined;
                    'marker-change-time'?: number | undefined;
                    'number-up'?: number | undefined;
                    'printer-commands'?: string | undefined;
                    'printer-info'?: string | undefined;
                    'printer-is-accepting-jobs'?: boolean | undefined;
                    'printer-is-shared'?: boolean | undefined;
                    'printer-is-temporary'?: boolean | undefined;
                    'printer-location'?: string | undefined;
                    'printer-make-and-model'?: string | undefined;
                    'printer-state'?: number | undefined;
                    'printer-state-change-time'?: number | undefined;
                    'printer-state-reasons'?: string | undefined;
                    'printer-type'?: number | undefined;
                    'printer-uri-supported'?: string | undefined;
                    system_driverinfo?: string | undefined;
                } | undefined;
            }[] | undefined;
            printersDefault?: {
                name: string;
                displayName: string;
                description: string;
                status: number;
                isDefault: boolean;
                options?: {
                    copies?: string | undefined;
                    'device-uri'?: string | undefined;
                    finishings?: string | undefined;
                    'job-cancel-after'?: number | undefined;
                    'job-hold-until'?: string | undefined;
                    'job-priority'?: number | undefined;
                    'job-sheets'?: string | undefined;
                    'marker-change-time'?: number | undefined;
                    'number-up'?: number | undefined;
                    'printer-commands'?: string | undefined;
                    'printer-info'?: string | undefined;
                    'printer-is-accepting-jobs'?: boolean | undefined;
                    'printer-is-shared'?: boolean | undefined;
                    'printer-is-temporary'?: boolean | undefined;
                    'printer-location'?: string | undefined;
                    'printer-make-and-model'?: string | undefined;
                    'printer-state'?: number | undefined;
                    'printer-state-change-time'?: number | undefined;
                    'printer-state-reasons'?: string | undefined;
                    'printer-type'?: number | undefined;
                    'printer-uri-supported'?: string | undefined;
                    system_driverinfo?: string | undefined;
                } | undefined;
            } | undefined;
        }[];
    }>;
    reloadDatabase: () => Promise<void>;
    reloadMain: () => Promise<void>;
    lowdb: import("lowdb/lib").LowSync<import("../declarations/LordStore").lordData>;
    reloadLowDB: () => void;
}, "dbPath" | "db" | "lowdb">>, Pick<{
    dbPath: string;
    db: globalThis.Ref<{
        id: string;
        ip: string;
        username: string | null;
        computerName: string | undefined;
        defaultPrinter: {
            name: string;
            displayName: string;
            description: string;
            status: number;
            isDefault: boolean;
            options?: {
                copies?: string | undefined;
                'device-uri'?: string | undefined;
                finishings?: string | undefined;
                'job-cancel-after'?: number | undefined;
                'job-hold-until'?: string | undefined;
                'job-priority'?: number | undefined;
                'job-sheets'?: string | undefined;
                'marker-change-time'?: number | undefined;
                'number-up'?: number | undefined;
                'printer-commands'?: string | undefined;
                'printer-info'?: string | undefined;
                'printer-is-accepting-jobs'?: boolean | undefined;
                'printer-is-shared'?: boolean | undefined;
                'printer-is-temporary'?: boolean | undefined;
                'printer-location'?: string | undefined;
                'printer-make-and-model'?: string | undefined;
                'printer-state'?: number | undefined;
                'printer-state-change-time'?: number | undefined;
                'printer-state-reasons'?: string | undefined;
                'printer-type'?: number | undefined;
                'printer-uri-supported'?: string | undefined;
                system_driverinfo?: string | undefined;
            } | undefined;
        } | null;
        printers: {
            name: string;
            displayName: string;
            description: string;
            status: number;
            isDefault: boolean;
            options?: {
                copies?: string | undefined;
                'device-uri'?: string | undefined;
                finishings?: string | undefined;
                'job-cancel-after'?: number | undefined;
                'job-hold-until'?: string | undefined;
                'job-priority'?: number | undefined;
                'job-sheets'?: string | undefined;
                'marker-change-time'?: number | undefined;
                'number-up'?: number | undefined;
                'printer-commands'?: string | undefined;
                'printer-info'?: string | undefined;
                'printer-is-accepting-jobs'?: boolean | undefined;
                'printer-is-shared'?: boolean | undefined;
                'printer-is-temporary'?: boolean | undefined;
                'printer-location'?: string | undefined;
                'printer-make-and-model'?: string | undefined;
                'printer-state'?: number | undefined;
                'printer-state-change-time'?: number | undefined;
                'printer-state-reasons'?: string | undefined;
                'printer-type'?: number | undefined;
                'printer-uri-supported'?: string | undefined;
                system_driverinfo?: string | undefined;
            } | undefined;
        }[];
        toPrintsCommands: {
            originalName?: string | undefined;
            encoding: string;
            mimetype: string;
            destination: string;
            filename: string;
            path: string;
            size: number;
            printOptions?: {
                printer?: string | undefined;
                pages?: string | undefined;
                subset?: string | undefined;
                orientation?: string | undefined;
                scale?: string | undefined;
                monochrome?: boolean | undefined;
                side?: string | undefined;
                bin?: string | undefined;
                paperSize?: string | undefined;
                silent?: boolean | undefined;
                printDialog?: boolean | undefined;
                sumatraPdfPath?: string | undefined;
                copies?: number | undefined;
            } | null | undefined;
            addedBy?: (string | null) | undefined;
            addedTo?: (string | null) | undefined;
            isPrinted: boolean;
            addedTime: Date | number;
            printerName?: string | undefined;
        }[];
        trashes: {
            originalName?: string | undefined;
            encoding: string;
            mimetype: string;
            destination: string;
            filename: string;
            path: string;
            size: number;
            printOptions?: {
                printer?: string | undefined;
                pages?: string | undefined;
                subset?: string | undefined;
                orientation?: string | undefined;
                scale?: string | undefined;
                monochrome?: boolean | undefined;
                side?: string | undefined;
                bin?: string | undefined;
                paperSize?: string | undefined;
                silent?: boolean | undefined;
                printDialog?: boolean | undefined;
                sumatraPdfPath?: string | undefined;
                copies?: number | undefined;
            } | null | undefined;
            addedBy?: (string | null) | undefined;
            addedTo?: (string | null) | undefined;
            isPrinted: boolean;
            addedTime: Date | number;
            printerName?: string | undefined;
            trashedBy: string | null;
            trashedTime: Date | number | null;
            isDeleted: boolean;
            deletedBy?: (string | null) | undefined;
            deletedTime?: (Date | number | null) | undefined;
        }[];
        lastPrinted: Date | number;
        ConnectedPCs: {
            id?: string | undefined;
            ip: string;
            username?: (string | null) | undefined;
            computerName: string | undefined;
            lastSeen?: (Date | number) | undefined;
            lastPrinted?: (Date | number) | undefined;
            isConnected?: boolean | undefined;
            printers?: {
                name: string;
                displayName: string;
                description: string;
                status: number;
                isDefault: boolean;
                options?: {
                    copies?: string | undefined;
                    'device-uri'?: string | undefined;
                    finishings?: string | undefined;
                    'job-cancel-after'?: number | undefined;
                    'job-hold-until'?: string | undefined;
                    'job-priority'?: number | undefined;
                    'job-sheets'?: string | undefined;
                    'marker-change-time'?: number | undefined;
                    'number-up'?: number | undefined;
                    'printer-commands'?: string | undefined;
                    'printer-info'?: string | undefined;
                    'printer-is-accepting-jobs'?: boolean | undefined;
                    'printer-is-shared'?: boolean | undefined;
                    'printer-is-temporary'?: boolean | undefined;
                    'printer-location'?: string | undefined;
                    'printer-make-and-model'?: string | undefined;
                    'printer-state'?: number | undefined;
                    'printer-state-change-time'?: number | undefined;
                    'printer-state-reasons'?: string | undefined;
                    'printer-type'?: number | undefined;
                    'printer-uri-supported'?: string | undefined;
                    system_driverinfo?: string | undefined;
                } | undefined;
            }[] | undefined;
            printersDefault?: {
                name: string;
                displayName: string;
                description: string;
                status: number;
                isDefault: boolean;
                options?: {
                    copies?: string | undefined;
                    'device-uri'?: string | undefined;
                    finishings?: string | undefined;
                    'job-cancel-after'?: number | undefined;
                    'job-hold-until'?: string | undefined;
                    'job-priority'?: number | undefined;
                    'job-sheets'?: string | undefined;
                    'marker-change-time'?: number | undefined;
                    'number-up'?: number | undefined;
                    'printer-commands'?: string | undefined;
                    'printer-info'?: string | undefined;
                    'printer-is-accepting-jobs'?: boolean | undefined;
                    'printer-is-shared'?: boolean | undefined;
                    'printer-is-temporary'?: boolean | undefined;
                    'printer-location'?: string | undefined;
                    'printer-make-and-model'?: string | undefined;
                    'printer-state'?: number | undefined;
                    'printer-state-change-time'?: number | undefined;
                    'printer-state-reasons'?: string | undefined;
                    'printer-type'?: number | undefined;
                    'printer-uri-supported'?: string | undefined;
                    system_driverinfo?: string | undefined;
                } | undefined;
            } | undefined;
        }[];
        recentlyConnectedPCs: {
            id?: string | undefined;
            ip: string;
            username?: (string | null) | undefined;
            computerName: string | undefined;
            lastSeen?: (Date | number) | undefined;
            lastPrinted?: (Date | number) | undefined;
            isConnected?: boolean | undefined;
            printers?: {
                name: string;
                displayName: string;
                description: string;
                status: number;
                isDefault: boolean;
                options?: {
                    copies?: string | undefined;
                    'device-uri'?: string | undefined;
                    finishings?: string | undefined;
                    'job-cancel-after'?: number | undefined;
                    'job-hold-until'?: string | undefined;
                    'job-priority'?: number | undefined;
                    'job-sheets'?: string | undefined;
                    'marker-change-time'?: number | undefined;
                    'number-up'?: number | undefined;
                    'printer-commands'?: string | undefined;
                    'printer-info'?: string | undefined;
                    'printer-is-accepting-jobs'?: boolean | undefined;
                    'printer-is-shared'?: boolean | undefined;
                    'printer-is-temporary'?: boolean | undefined;
                    'printer-location'?: string | undefined;
                    'printer-make-and-model'?: string | undefined;
                    'printer-state'?: number | undefined;
                    'printer-state-change-time'?: number | undefined;
                    'printer-state-reasons'?: string | undefined;
                    'printer-type'?: number | undefined;
                    'printer-uri-supported'?: string | undefined;
                    system_driverinfo?: string | undefined;
                } | undefined;
            }[] | undefined;
            printersDefault?: {
                name: string;
                displayName: string;
                description: string;
                status: number;
                isDefault: boolean;
                options?: {
                    copies?: string | undefined;
                    'device-uri'?: string | undefined;
                    finishings?: string | undefined;
                    'job-cancel-after'?: number | undefined;
                    'job-hold-until'?: string | undefined;
                    'job-priority'?: number | undefined;
                    'job-sheets'?: string | undefined;
                    'marker-change-time'?: number | undefined;
                    'number-up'?: number | undefined;
                    'printer-commands'?: string | undefined;
                    'printer-info'?: string | undefined;
                    'printer-is-accepting-jobs'?: boolean | undefined;
                    'printer-is-shared'?: boolean | undefined;
                    'printer-is-temporary'?: boolean | undefined;
                    'printer-location'?: string | undefined;
                    'printer-make-and-model'?: string | undefined;
                    'printer-state'?: number | undefined;
                    'printer-state-change-time'?: number | undefined;
                    'printer-state-reasons'?: string | undefined;
                    'printer-type'?: number | undefined;
                    'printer-uri-supported'?: string | undefined;
                    system_driverinfo?: string | undefined;
                } | undefined;
            } | undefined;
        }[];
        lastCheckConnectedPC: Date | number;
        offlineComputers: {
            id?: string | undefined;
            ip: string;
            username?: (string | null) | undefined;
            computerName: string | undefined;
            lastSeen?: (Date | number) | undefined;
            lastPrinted?: (Date | number) | undefined;
            isConnected?: boolean | undefined;
            printers?: {
                name: string;
                displayName: string;
                description: string;
                status: number;
                isDefault: boolean;
                options?: {
                    copies?: string | undefined;
                    'device-uri'?: string | undefined;
                    finishings?: string | undefined;
                    'job-cancel-after'?: number | undefined;
                    'job-hold-until'?: string | undefined;
                    'job-priority'?: number | undefined;
                    'job-sheets'?: string | undefined;
                    'marker-change-time'?: number | undefined;
                    'number-up'?: number | undefined;
                    'printer-commands'?: string | undefined;
                    'printer-info'?: string | undefined;
                    'printer-is-accepting-jobs'?: boolean | undefined;
                    'printer-is-shared'?: boolean | undefined;
                    'printer-is-temporary'?: boolean | undefined;
                    'printer-location'?: string | undefined;
                    'printer-make-and-model'?: string | undefined;
                    'printer-state'?: number | undefined;
                    'printer-state-change-time'?: number | undefined;
                    'printer-state-reasons'?: string | undefined;
                    'printer-type'?: number | undefined;
                    'printer-uri-supported'?: string | undefined;
                    system_driverinfo?: string | undefined;
                } | undefined;
            }[] | undefined;
            printersDefault?: {
                name: string;
                displayName: string;
                description: string;
                status: number;
                isDefault: boolean;
                options?: {
                    copies?: string | undefined;
                    'device-uri'?: string | undefined;
                    finishings?: string | undefined;
                    'job-cancel-after'?: number | undefined;
                    'job-hold-until'?: string | undefined;
                    'job-priority'?: number | undefined;
                    'job-sheets'?: string | undefined;
                    'marker-change-time'?: number | undefined;
                    'number-up'?: number | undefined;
                    'printer-commands'?: string | undefined;
                    'printer-info'?: string | undefined;
                    'printer-is-accepting-jobs'?: boolean | undefined;
                    'printer-is-shared'?: boolean | undefined;
                    'printer-is-temporary'?: boolean | undefined;
                    'printer-location'?: string | undefined;
                    'printer-make-and-model'?: string | undefined;
                    'printer-state'?: number | undefined;
                    'printer-state-change-time'?: number | undefined;
                    'printer-state-reasons'?: string | undefined;
                    'printer-type'?: number | undefined;
                    'printer-uri-supported'?: string | undefined;
                    system_driverinfo?: string | undefined;
                } | undefined;
            } | undefined;
        }[];
    }, import("../declarations/LordStore").lordData | {
        id: string;
        ip: string;
        username: string | null;
        computerName: string | undefined;
        defaultPrinter: {
            name: string;
            displayName: string;
            description: string;
            status: number;
            isDefault: boolean;
            options?: {
                copies?: string | undefined;
                'device-uri'?: string | undefined;
                finishings?: string | undefined;
                'job-cancel-after'?: number | undefined;
                'job-hold-until'?: string | undefined;
                'job-priority'?: number | undefined;
                'job-sheets'?: string | undefined;
                'marker-change-time'?: number | undefined;
                'number-up'?: number | undefined;
                'printer-commands'?: string | undefined;
                'printer-info'?: string | undefined;
                'printer-is-accepting-jobs'?: boolean | undefined;
                'printer-is-shared'?: boolean | undefined;
                'printer-is-temporary'?: boolean | undefined;
                'printer-location'?: string | undefined;
                'printer-make-and-model'?: string | undefined;
                'printer-state'?: number | undefined;
                'printer-state-change-time'?: number | undefined;
                'printer-state-reasons'?: string | undefined;
                'printer-type'?: number | undefined;
                'printer-uri-supported'?: string | undefined;
                system_driverinfo?: string | undefined;
            } | undefined;
        } | null;
        printers: {
            name: string;
            displayName: string;
            description: string;
            status: number;
            isDefault: boolean;
            options?: {
                copies?: string | undefined;
                'device-uri'?: string | undefined;
                finishings?: string | undefined;
                'job-cancel-after'?: number | undefined;
                'job-hold-until'?: string | undefined;
                'job-priority'?: number | undefined;
                'job-sheets'?: string | undefined;
                'marker-change-time'?: number | undefined;
                'number-up'?: number | undefined;
                'printer-commands'?: string | undefined;
                'printer-info'?: string | undefined;
                'printer-is-accepting-jobs'?: boolean | undefined;
                'printer-is-shared'?: boolean | undefined;
                'printer-is-temporary'?: boolean | undefined;
                'printer-location'?: string | undefined;
                'printer-make-and-model'?: string | undefined;
                'printer-state'?: number | undefined;
                'printer-state-change-time'?: number | undefined;
                'printer-state-reasons'?: string | undefined;
                'printer-type'?: number | undefined;
                'printer-uri-supported'?: string | undefined;
                system_driverinfo?: string | undefined;
            } | undefined;
        }[];
        toPrintsCommands: {
            originalName?: string | undefined;
            encoding: string;
            mimetype: string;
            destination: string;
            filename: string;
            path: string;
            size: number;
            printOptions?: {
                printer?: string | undefined;
                pages?: string | undefined;
                subset?: string | undefined;
                orientation?: string | undefined;
                scale?: string | undefined;
                monochrome?: boolean | undefined;
                side?: string | undefined;
                bin?: string | undefined;
                paperSize?: string | undefined;
                silent?: boolean | undefined;
                printDialog?: boolean | undefined;
                sumatraPdfPath?: string | undefined;
                copies?: number | undefined;
            } | null | undefined;
            addedBy?: (string | null) | undefined;
            addedTo?: (string | null) | undefined;
            isPrinted: boolean;
            addedTime: Date | number;
            printerName?: string | undefined;
        }[];
        trashes: {
            originalName?: string | undefined;
            encoding: string;
            mimetype: string;
            destination: string;
            filename: string;
            path: string;
            size: number;
            printOptions?: {
                printer?: string | undefined;
                pages?: string | undefined;
                subset?: string | undefined;
                orientation?: string | undefined;
                scale?: string | undefined;
                monochrome?: boolean | undefined;
                side?: string | undefined;
                bin?: string | undefined;
                paperSize?: string | undefined;
                silent?: boolean | undefined;
                printDialog?: boolean | undefined;
                sumatraPdfPath?: string | undefined;
                copies?: number | undefined;
            } | null | undefined;
            addedBy?: (string | null) | undefined;
            addedTo?: (string | null) | undefined;
            isPrinted: boolean;
            addedTime: Date | number;
            printerName?: string | undefined;
            trashedBy: string | null;
            trashedTime: Date | number | null;
            isDeleted: boolean;
            deletedBy?: (string | null) | undefined;
            deletedTime?: (Date | number | null) | undefined;
        }[];
        lastPrinted: Date | number;
        ConnectedPCs: {
            id?: string | undefined;
            ip: string;
            username?: (string | null) | undefined;
            computerName: string | undefined;
            lastSeen?: (Date | number) | undefined;
            lastPrinted?: (Date | number) | undefined;
            isConnected?: boolean | undefined;
            printers?: {
                name: string;
                displayName: string;
                description: string;
                status: number;
                isDefault: boolean;
                options?: {
                    copies?: string | undefined;
                    'device-uri'?: string | undefined;
                    finishings?: string | undefined;
                    'job-cancel-after'?: number | undefined;
                    'job-hold-until'?: string | undefined;
                    'job-priority'?: number | undefined;
                    'job-sheets'?: string | undefined;
                    'marker-change-time'?: number | undefined;
                    'number-up'?: number | undefined;
                    'printer-commands'?: string | undefined;
                    'printer-info'?: string | undefined;
                    'printer-is-accepting-jobs'?: boolean | undefined;
                    'printer-is-shared'?: boolean | undefined;
                    'printer-is-temporary'?: boolean | undefined;
                    'printer-location'?: string | undefined;
                    'printer-make-and-model'?: string | undefined;
                    'printer-state'?: number | undefined;
                    'printer-state-change-time'?: number | undefined;
                    'printer-state-reasons'?: string | undefined;
                    'printer-type'?: number | undefined;
                    'printer-uri-supported'?: string | undefined;
                    system_driverinfo?: string | undefined;
                } | undefined;
            }[] | undefined;
            printersDefault?: {
                name: string;
                displayName: string;
                description: string;
                status: number;
                isDefault: boolean;
                options?: {
                    copies?: string | undefined;
                    'device-uri'?: string | undefined;
                    finishings?: string | undefined;
                    'job-cancel-after'?: number | undefined;
                    'job-hold-until'?: string | undefined;
                    'job-priority'?: number | undefined;
                    'job-sheets'?: string | undefined;
                    'marker-change-time'?: number | undefined;
                    'number-up'?: number | undefined;
                    'printer-commands'?: string | undefined;
                    'printer-info'?: string | undefined;
                    'printer-is-accepting-jobs'?: boolean | undefined;
                    'printer-is-shared'?: boolean | undefined;
                    'printer-is-temporary'?: boolean | undefined;
                    'printer-location'?: string | undefined;
                    'printer-make-and-model'?: string | undefined;
                    'printer-state'?: number | undefined;
                    'printer-state-change-time'?: number | undefined;
                    'printer-state-reasons'?: string | undefined;
                    'printer-type'?: number | undefined;
                    'printer-uri-supported'?: string | undefined;
                    system_driverinfo?: string | undefined;
                } | undefined;
            } | undefined;
        }[];
        recentlyConnectedPCs: {
            id?: string | undefined;
            ip: string;
            username?: (string | null) | undefined;
            computerName: string | undefined;
            lastSeen?: (Date | number) | undefined;
            lastPrinted?: (Date | number) | undefined;
            isConnected?: boolean | undefined;
            printers?: {
                name: string;
                displayName: string;
                description: string;
                status: number;
                isDefault: boolean;
                options?: {
                    copies?: string | undefined;
                    'device-uri'?: string | undefined;
                    finishings?: string | undefined;
                    'job-cancel-after'?: number | undefined;
                    'job-hold-until'?: string | undefined;
                    'job-priority'?: number | undefined;
                    'job-sheets'?: string | undefined;
                    'marker-change-time'?: number | undefined;
                    'number-up'?: number | undefined;
                    'printer-commands'?: string | undefined;
                    'printer-info'?: string | undefined;
                    'printer-is-accepting-jobs'?: boolean | undefined;
                    'printer-is-shared'?: boolean | undefined;
                    'printer-is-temporary'?: boolean | undefined;
                    'printer-location'?: string | undefined;
                    'printer-make-and-model'?: string | undefined;
                    'printer-state'?: number | undefined;
                    'printer-state-change-time'?: number | undefined;
                    'printer-state-reasons'?: string | undefined;
                    'printer-type'?: number | undefined;
                    'printer-uri-supported'?: string | undefined;
                    system_driverinfo?: string | undefined;
                } | undefined;
            }[] | undefined;
            printersDefault?: {
                name: string;
                displayName: string;
                description: string;
                status: number;
                isDefault: boolean;
                options?: {
                    copies?: string | undefined;
                    'device-uri'?: string | undefined;
                    finishings?: string | undefined;
                    'job-cancel-after'?: number | undefined;
                    'job-hold-until'?: string | undefined;
                    'job-priority'?: number | undefined;
                    'job-sheets'?: string | undefined;
                    'marker-change-time'?: number | undefined;
                    'number-up'?: number | undefined;
                    'printer-commands'?: string | undefined;
                    'printer-info'?: string | undefined;
                    'printer-is-accepting-jobs'?: boolean | undefined;
                    'printer-is-shared'?: boolean | undefined;
                    'printer-is-temporary'?: boolean | undefined;
                    'printer-location'?: string | undefined;
                    'printer-make-and-model'?: string | undefined;
                    'printer-state'?: number | undefined;
                    'printer-state-change-time'?: number | undefined;
                    'printer-state-reasons'?: string | undefined;
                    'printer-type'?: number | undefined;
                    'printer-uri-supported'?: string | undefined;
                    system_driverinfo?: string | undefined;
                } | undefined;
            } | undefined;
        }[];
        lastCheckConnectedPC: Date | number;
        offlineComputers: {
            id?: string | undefined;
            ip: string;
            username?: (string | null) | undefined;
            computerName: string | undefined;
            lastSeen?: (Date | number) | undefined;
            lastPrinted?: (Date | number) | undefined;
            isConnected?: boolean | undefined;
            printers?: {
                name: string;
                displayName: string;
                description: string;
                status: number;
                isDefault: boolean;
                options?: {
                    copies?: string | undefined;
                    'device-uri'?: string | undefined;
                    finishings?: string | undefined;
                    'job-cancel-after'?: number | undefined;
                    'job-hold-until'?: string | undefined;
                    'job-priority'?: number | undefined;
                    'job-sheets'?: string | undefined;
                    'marker-change-time'?: number | undefined;
                    'number-up'?: number | undefined;
                    'printer-commands'?: string | undefined;
                    'printer-info'?: string | undefined;
                    'printer-is-accepting-jobs'?: boolean | undefined;
                    'printer-is-shared'?: boolean | undefined;
                    'printer-is-temporary'?: boolean | undefined;
                    'printer-location'?: string | undefined;
                    'printer-make-and-model'?: string | undefined;
                    'printer-state'?: number | undefined;
                    'printer-state-change-time'?: number | undefined;
                    'printer-state-reasons'?: string | undefined;
                    'printer-type'?: number | undefined;
                    'printer-uri-supported'?: string | undefined;
                    system_driverinfo?: string | undefined;
                } | undefined;
            }[] | undefined;
            printersDefault?: {
                name: string;
                displayName: string;
                description: string;
                status: number;
                isDefault: boolean;
                options?: {
                    copies?: string | undefined;
                    'device-uri'?: string | undefined;
                    finishings?: string | undefined;
                    'job-cancel-after'?: number | undefined;
                    'job-hold-until'?: string | undefined;
                    'job-priority'?: number | undefined;
                    'job-sheets'?: string | undefined;
                    'marker-change-time'?: number | undefined;
                    'number-up'?: number | undefined;
                    'printer-commands'?: string | undefined;
                    'printer-info'?: string | undefined;
                    'printer-is-accepting-jobs'?: boolean | undefined;
                    'printer-is-shared'?: boolean | undefined;
                    'printer-is-temporary'?: boolean | undefined;
                    'printer-location'?: string | undefined;
                    'printer-make-and-model'?: string | undefined;
                    'printer-state'?: number | undefined;
                    'printer-state-change-time'?: number | undefined;
                    'printer-state-reasons'?: string | undefined;
                    'printer-type'?: number | undefined;
                    'printer-uri-supported'?: string | undefined;
                    system_driverinfo?: string | undefined;
                } | undefined;
            } | undefined;
        }[];
    }>;
    reloadDatabase: () => Promise<void>;
    reloadMain: () => Promise<void>;
    lowdb: import("lowdb/lib").LowSync<import("../declarations/LordStore").lordData>;
    reloadLowDB: () => void;
}, never>, Pick<{
    dbPath: string;
    db: globalThis.Ref<{
        id: string;
        ip: string;
        username: string | null;
        computerName: string | undefined;
        defaultPrinter: {
            name: string;
            displayName: string;
            description: string;
            status: number;
            isDefault: boolean;
            options?: {
                copies?: string | undefined;
                'device-uri'?: string | undefined;
                finishings?: string | undefined;
                'job-cancel-after'?: number | undefined;
                'job-hold-until'?: string | undefined;
                'job-priority'?: number | undefined;
                'job-sheets'?: string | undefined;
                'marker-change-time'?: number | undefined;
                'number-up'?: number | undefined;
                'printer-commands'?: string | undefined;
                'printer-info'?: string | undefined;
                'printer-is-accepting-jobs'?: boolean | undefined;
                'printer-is-shared'?: boolean | undefined;
                'printer-is-temporary'?: boolean | undefined;
                'printer-location'?: string | undefined;
                'printer-make-and-model'?: string | undefined;
                'printer-state'?: number | undefined;
                'printer-state-change-time'?: number | undefined;
                'printer-state-reasons'?: string | undefined;
                'printer-type'?: number | undefined;
                'printer-uri-supported'?: string | undefined;
                system_driverinfo?: string | undefined;
            } | undefined;
        } | null;
        printers: {
            name: string;
            displayName: string;
            description: string;
            status: number;
            isDefault: boolean;
            options?: {
                copies?: string | undefined;
                'device-uri'?: string | undefined;
                finishings?: string | undefined;
                'job-cancel-after'?: number | undefined;
                'job-hold-until'?: string | undefined;
                'job-priority'?: number | undefined;
                'job-sheets'?: string | undefined;
                'marker-change-time'?: number | undefined;
                'number-up'?: number | undefined;
                'printer-commands'?: string | undefined;
                'printer-info'?: string | undefined;
                'printer-is-accepting-jobs'?: boolean | undefined;
                'printer-is-shared'?: boolean | undefined;
                'printer-is-temporary'?: boolean | undefined;
                'printer-location'?: string | undefined;
                'printer-make-and-model'?: string | undefined;
                'printer-state'?: number | undefined;
                'printer-state-change-time'?: number | undefined;
                'printer-state-reasons'?: string | undefined;
                'printer-type'?: number | undefined;
                'printer-uri-supported'?: string | undefined;
                system_driverinfo?: string | undefined;
            } | undefined;
        }[];
        toPrintsCommands: {
            originalName?: string | undefined;
            encoding: string;
            mimetype: string;
            destination: string;
            filename: string;
            path: string;
            size: number;
            printOptions?: {
                printer?: string | undefined;
                pages?: string | undefined;
                subset?: string | undefined;
                orientation?: string | undefined;
                scale?: string | undefined;
                monochrome?: boolean | undefined;
                side?: string | undefined;
                bin?: string | undefined;
                paperSize?: string | undefined;
                silent?: boolean | undefined;
                printDialog?: boolean | undefined;
                sumatraPdfPath?: string | undefined;
                copies?: number | undefined;
            } | null | undefined;
            addedBy?: (string | null) | undefined;
            addedTo?: (string | null) | undefined;
            isPrinted: boolean;
            addedTime: Date | number;
            printerName?: string | undefined;
        }[];
        trashes: {
            originalName?: string | undefined;
            encoding: string;
            mimetype: string;
            destination: string;
            filename: string;
            path: string;
            size: number;
            printOptions?: {
                printer?: string | undefined;
                pages?: string | undefined;
                subset?: string | undefined;
                orientation?: string | undefined;
                scale?: string | undefined;
                monochrome?: boolean | undefined;
                side?: string | undefined;
                bin?: string | undefined;
                paperSize?: string | undefined;
                silent?: boolean | undefined;
                printDialog?: boolean | undefined;
                sumatraPdfPath?: string | undefined;
                copies?: number | undefined;
            } | null | undefined;
            addedBy?: (string | null) | undefined;
            addedTo?: (string | null) | undefined;
            isPrinted: boolean;
            addedTime: Date | number;
            printerName?: string | undefined;
            trashedBy: string | null;
            trashedTime: Date | number | null;
            isDeleted: boolean;
            deletedBy?: (string | null) | undefined;
            deletedTime?: (Date | number | null) | undefined;
        }[];
        lastPrinted: Date | number;
        ConnectedPCs: {
            id?: string | undefined;
            ip: string;
            username?: (string | null) | undefined;
            computerName: string | undefined;
            lastSeen?: (Date | number) | undefined;
            lastPrinted?: (Date | number) | undefined;
            isConnected?: boolean | undefined;
            printers?: {
                name: string;
                displayName: string;
                description: string;
                status: number;
                isDefault: boolean;
                options?: {
                    copies?: string | undefined;
                    'device-uri'?: string | undefined;
                    finishings?: string | undefined;
                    'job-cancel-after'?: number | undefined;
                    'job-hold-until'?: string | undefined;
                    'job-priority'?: number | undefined;
                    'job-sheets'?: string | undefined;
                    'marker-change-time'?: number | undefined;
                    'number-up'?: number | undefined;
                    'printer-commands'?: string | undefined;
                    'printer-info'?: string | undefined;
                    'printer-is-accepting-jobs'?: boolean | undefined;
                    'printer-is-shared'?: boolean | undefined;
                    'printer-is-temporary'?: boolean | undefined;
                    'printer-location'?: string | undefined;
                    'printer-make-and-model'?: string | undefined;
                    'printer-state'?: number | undefined;
                    'printer-state-change-time'?: number | undefined;
                    'printer-state-reasons'?: string | undefined;
                    'printer-type'?: number | undefined;
                    'printer-uri-supported'?: string | undefined;
                    system_driverinfo?: string | undefined;
                } | undefined;
            }[] | undefined;
            printersDefault?: {
                name: string;
                displayName: string;
                description: string;
                status: number;
                isDefault: boolean;
                options?: {
                    copies?: string | undefined;
                    'device-uri'?: string | undefined;
                    finishings?: string | undefined;
                    'job-cancel-after'?: number | undefined;
                    'job-hold-until'?: string | undefined;
                    'job-priority'?: number | undefined;
                    'job-sheets'?: string | undefined;
                    'marker-change-time'?: number | undefined;
                    'number-up'?: number | undefined;
                    'printer-commands'?: string | undefined;
                    'printer-info'?: string | undefined;
                    'printer-is-accepting-jobs'?: boolean | undefined;
                    'printer-is-shared'?: boolean | undefined;
                    'printer-is-temporary'?: boolean | undefined;
                    'printer-location'?: string | undefined;
                    'printer-make-and-model'?: string | undefined;
                    'printer-state'?: number | undefined;
                    'printer-state-change-time'?: number | undefined;
                    'printer-state-reasons'?: string | undefined;
                    'printer-type'?: number | undefined;
                    'printer-uri-supported'?: string | undefined;
                    system_driverinfo?: string | undefined;
                } | undefined;
            } | undefined;
        }[];
        recentlyConnectedPCs: {
            id?: string | undefined;
            ip: string;
            username?: (string | null) | undefined;
            computerName: string | undefined;
            lastSeen?: (Date | number) | undefined;
            lastPrinted?: (Date | number) | undefined;
            isConnected?: boolean | undefined;
            printers?: {
                name: string;
                displayName: string;
                description: string;
                status: number;
                isDefault: boolean;
                options?: {
                    copies?: string | undefined;
                    'device-uri'?: string | undefined;
                    finishings?: string | undefined;
                    'job-cancel-after'?: number | undefined;
                    'job-hold-until'?: string | undefined;
                    'job-priority'?: number | undefined;
                    'job-sheets'?: string | undefined;
                    'marker-change-time'?: number | undefined;
                    'number-up'?: number | undefined;
                    'printer-commands'?: string | undefined;
                    'printer-info'?: string | undefined;
                    'printer-is-accepting-jobs'?: boolean | undefined;
                    'printer-is-shared'?: boolean | undefined;
                    'printer-is-temporary'?: boolean | undefined;
                    'printer-location'?: string | undefined;
                    'printer-make-and-model'?: string | undefined;
                    'printer-state'?: number | undefined;
                    'printer-state-change-time'?: number | undefined;
                    'printer-state-reasons'?: string | undefined;
                    'printer-type'?: number | undefined;
                    'printer-uri-supported'?: string | undefined;
                    system_driverinfo?: string | undefined;
                } | undefined;
            }[] | undefined;
            printersDefault?: {
                name: string;
                displayName: string;
                description: string;
                status: number;
                isDefault: boolean;
                options?: {
                    copies?: string | undefined;
                    'device-uri'?: string | undefined;
                    finishings?: string | undefined;
                    'job-cancel-after'?: number | undefined;
                    'job-hold-until'?: string | undefined;
                    'job-priority'?: number | undefined;
                    'job-sheets'?: string | undefined;
                    'marker-change-time'?: number | undefined;
                    'number-up'?: number | undefined;
                    'printer-commands'?: string | undefined;
                    'printer-info'?: string | undefined;
                    'printer-is-accepting-jobs'?: boolean | undefined;
                    'printer-is-shared'?: boolean | undefined;
                    'printer-is-temporary'?: boolean | undefined;
                    'printer-location'?: string | undefined;
                    'printer-make-and-model'?: string | undefined;
                    'printer-state'?: number | undefined;
                    'printer-state-change-time'?: number | undefined;
                    'printer-state-reasons'?: string | undefined;
                    'printer-type'?: number | undefined;
                    'printer-uri-supported'?: string | undefined;
                    system_driverinfo?: string | undefined;
                } | undefined;
            } | undefined;
        }[];
        lastCheckConnectedPC: Date | number;
        offlineComputers: {
            id?: string | undefined;
            ip: string;
            username?: (string | null) | undefined;
            computerName: string | undefined;
            lastSeen?: (Date | number) | undefined;
            lastPrinted?: (Date | number) | undefined;
            isConnected?: boolean | undefined;
            printers?: {
                name: string;
                displayName: string;
                description: string;
                status: number;
                isDefault: boolean;
                options?: {
                    copies?: string | undefined;
                    'device-uri'?: string | undefined;
                    finishings?: string | undefined;
                    'job-cancel-after'?: number | undefined;
                    'job-hold-until'?: string | undefined;
                    'job-priority'?: number | undefined;
                    'job-sheets'?: string | undefined;
                    'marker-change-time'?: number | undefined;
                    'number-up'?: number | undefined;
                    'printer-commands'?: string | undefined;
                    'printer-info'?: string | undefined;
                    'printer-is-accepting-jobs'?: boolean | undefined;
                    'printer-is-shared'?: boolean | undefined;
                    'printer-is-temporary'?: boolean | undefined;
                    'printer-location'?: string | undefined;
                    'printer-make-and-model'?: string | undefined;
                    'printer-state'?: number | undefined;
                    'printer-state-change-time'?: number | undefined;
                    'printer-state-reasons'?: string | undefined;
                    'printer-type'?: number | undefined;
                    'printer-uri-supported'?: string | undefined;
                    system_driverinfo?: string | undefined;
                } | undefined;
            }[] | undefined;
            printersDefault?: {
                name: string;
                displayName: string;
                description: string;
                status: number;
                isDefault: boolean;
                options?: {
                    copies?: string | undefined;
                    'device-uri'?: string | undefined;
                    finishings?: string | undefined;
                    'job-cancel-after'?: number | undefined;
                    'job-hold-until'?: string | undefined;
                    'job-priority'?: number | undefined;
                    'job-sheets'?: string | undefined;
                    'marker-change-time'?: number | undefined;
                    'number-up'?: number | undefined;
                    'printer-commands'?: string | undefined;
                    'printer-info'?: string | undefined;
                    'printer-is-accepting-jobs'?: boolean | undefined;
                    'printer-is-shared'?: boolean | undefined;
                    'printer-is-temporary'?: boolean | undefined;
                    'printer-location'?: string | undefined;
                    'printer-make-and-model'?: string | undefined;
                    'printer-state'?: number | undefined;
                    'printer-state-change-time'?: number | undefined;
                    'printer-state-reasons'?: string | undefined;
                    'printer-type'?: number | undefined;
                    'printer-uri-supported'?: string | undefined;
                    system_driverinfo?: string | undefined;
                } | undefined;
            } | undefined;
        }[];
    }, import("../declarations/LordStore").lordData | {
        id: string;
        ip: string;
        username: string | null;
        computerName: string | undefined;
        defaultPrinter: {
            name: string;
            displayName: string;
            description: string;
            status: number;
            isDefault: boolean;
            options?: {
                copies?: string | undefined;
                'device-uri'?: string | undefined;
                finishings?: string | undefined;
                'job-cancel-after'?: number | undefined;
                'job-hold-until'?: string | undefined;
                'job-priority'?: number | undefined;
                'job-sheets'?: string | undefined;
                'marker-change-time'?: number | undefined;
                'number-up'?: number | undefined;
                'printer-commands'?: string | undefined;
                'printer-info'?: string | undefined;
                'printer-is-accepting-jobs'?: boolean | undefined;
                'printer-is-shared'?: boolean | undefined;
                'printer-is-temporary'?: boolean | undefined;
                'printer-location'?: string | undefined;
                'printer-make-and-model'?: string | undefined;
                'printer-state'?: number | undefined;
                'printer-state-change-time'?: number | undefined;
                'printer-state-reasons'?: string | undefined;
                'printer-type'?: number | undefined;
                'printer-uri-supported'?: string | undefined;
                system_driverinfo?: string | undefined;
            } | undefined;
        } | null;
        printers: {
            name: string;
            displayName: string;
            description: string;
            status: number;
            isDefault: boolean;
            options?: {
                copies?: string | undefined;
                'device-uri'?: string | undefined;
                finishings?: string | undefined;
                'job-cancel-after'?: number | undefined;
                'job-hold-until'?: string | undefined;
                'job-priority'?: number | undefined;
                'job-sheets'?: string | undefined;
                'marker-change-time'?: number | undefined;
                'number-up'?: number | undefined;
                'printer-commands'?: string | undefined;
                'printer-info'?: string | undefined;
                'printer-is-accepting-jobs'?: boolean | undefined;
                'printer-is-shared'?: boolean | undefined;
                'printer-is-temporary'?: boolean | undefined;
                'printer-location'?: string | undefined;
                'printer-make-and-model'?: string | undefined;
                'printer-state'?: number | undefined;
                'printer-state-change-time'?: number | undefined;
                'printer-state-reasons'?: string | undefined;
                'printer-type'?: number | undefined;
                'printer-uri-supported'?: string | undefined;
                system_driverinfo?: string | undefined;
            } | undefined;
        }[];
        toPrintsCommands: {
            originalName?: string | undefined;
            encoding: string;
            mimetype: string;
            destination: string;
            filename: string;
            path: string;
            size: number;
            printOptions?: {
                printer?: string | undefined;
                pages?: string | undefined;
                subset?: string | undefined;
                orientation?: string | undefined;
                scale?: string | undefined;
                monochrome?: boolean | undefined;
                side?: string | undefined;
                bin?: string | undefined;
                paperSize?: string | undefined;
                silent?: boolean | undefined;
                printDialog?: boolean | undefined;
                sumatraPdfPath?: string | undefined;
                copies?: number | undefined;
            } | null | undefined;
            addedBy?: (string | null) | undefined;
            addedTo?: (string | null) | undefined;
            isPrinted: boolean;
            addedTime: Date | number;
            printerName?: string | undefined;
        }[];
        trashes: {
            originalName?: string | undefined;
            encoding: string;
            mimetype: string;
            destination: string;
            filename: string;
            path: string;
            size: number;
            printOptions?: {
                printer?: string | undefined;
                pages?: string | undefined;
                subset?: string | undefined;
                orientation?: string | undefined;
                scale?: string | undefined;
                monochrome?: boolean | undefined;
                side?: string | undefined;
                bin?: string | undefined;
                paperSize?: string | undefined;
                silent?: boolean | undefined;
                printDialog?: boolean | undefined;
                sumatraPdfPath?: string | undefined;
                copies?: number | undefined;
            } | null | undefined;
            addedBy?: (string | null) | undefined;
            addedTo?: (string | null) | undefined;
            isPrinted: boolean;
            addedTime: Date | number;
            printerName?: string | undefined;
            trashedBy: string | null;
            trashedTime: Date | number | null;
            isDeleted: boolean;
            deletedBy?: (string | null) | undefined;
            deletedTime?: (Date | number | null) | undefined;
        }[];
        lastPrinted: Date | number;
        ConnectedPCs: {
            id?: string | undefined;
            ip: string;
            username?: (string | null) | undefined;
            computerName: string | undefined;
            lastSeen?: (Date | number) | undefined;
            lastPrinted?: (Date | number) | undefined;
            isConnected?: boolean | undefined;
            printers?: {
                name: string;
                displayName: string;
                description: string;
                status: number;
                isDefault: boolean;
                options?: {
                    copies?: string | undefined;
                    'device-uri'?: string | undefined;
                    finishings?: string | undefined;
                    'job-cancel-after'?: number | undefined;
                    'job-hold-until'?: string | undefined;
                    'job-priority'?: number | undefined;
                    'job-sheets'?: string | undefined;
                    'marker-change-time'?: number | undefined;
                    'number-up'?: number | undefined;
                    'printer-commands'?: string | undefined;
                    'printer-info'?: string | undefined;
                    'printer-is-accepting-jobs'?: boolean | undefined;
                    'printer-is-shared'?: boolean | undefined;
                    'printer-is-temporary'?: boolean | undefined;
                    'printer-location'?: string | undefined;
                    'printer-make-and-model'?: string | undefined;
                    'printer-state'?: number | undefined;
                    'printer-state-change-time'?: number | undefined;
                    'printer-state-reasons'?: string | undefined;
                    'printer-type'?: number | undefined;
                    'printer-uri-supported'?: string | undefined;
                    system_driverinfo?: string | undefined;
                } | undefined;
            }[] | undefined;
            printersDefault?: {
                name: string;
                displayName: string;
                description: string;
                status: number;
                isDefault: boolean;
                options?: {
                    copies?: string | undefined;
                    'device-uri'?: string | undefined;
                    finishings?: string | undefined;
                    'job-cancel-after'?: number | undefined;
                    'job-hold-until'?: string | undefined;
                    'job-priority'?: number | undefined;
                    'job-sheets'?: string | undefined;
                    'marker-change-time'?: number | undefined;
                    'number-up'?: number | undefined;
                    'printer-commands'?: string | undefined;
                    'printer-info'?: string | undefined;
                    'printer-is-accepting-jobs'?: boolean | undefined;
                    'printer-is-shared'?: boolean | undefined;
                    'printer-is-temporary'?: boolean | undefined;
                    'printer-location'?: string | undefined;
                    'printer-make-and-model'?: string | undefined;
                    'printer-state'?: number | undefined;
                    'printer-state-change-time'?: number | undefined;
                    'printer-state-reasons'?: string | undefined;
                    'printer-type'?: number | undefined;
                    'printer-uri-supported'?: string | undefined;
                    system_driverinfo?: string | undefined;
                } | undefined;
            } | undefined;
        }[];
        recentlyConnectedPCs: {
            id?: string | undefined;
            ip: string;
            username?: (string | null) | undefined;
            computerName: string | undefined;
            lastSeen?: (Date | number) | undefined;
            lastPrinted?: (Date | number) | undefined;
            isConnected?: boolean | undefined;
            printers?: {
                name: string;
                displayName: string;
                description: string;
                status: number;
                isDefault: boolean;
                options?: {
                    copies?: string | undefined;
                    'device-uri'?: string | undefined;
                    finishings?: string | undefined;
                    'job-cancel-after'?: number | undefined;
                    'job-hold-until'?: string | undefined;
                    'job-priority'?: number | undefined;
                    'job-sheets'?: string | undefined;
                    'marker-change-time'?: number | undefined;
                    'number-up'?: number | undefined;
                    'printer-commands'?: string | undefined;
                    'printer-info'?: string | undefined;
                    'printer-is-accepting-jobs'?: boolean | undefined;
                    'printer-is-shared'?: boolean | undefined;
                    'printer-is-temporary'?: boolean | undefined;
                    'printer-location'?: string | undefined;
                    'printer-make-and-model'?: string | undefined;
                    'printer-state'?: number | undefined;
                    'printer-state-change-time'?: number | undefined;
                    'printer-state-reasons'?: string | undefined;
                    'printer-type'?: number | undefined;
                    'printer-uri-supported'?: string | undefined;
                    system_driverinfo?: string | undefined;
                } | undefined;
            }[] | undefined;
            printersDefault?: {
                name: string;
                displayName: string;
                description: string;
                status: number;
                isDefault: boolean;
                options?: {
                    copies?: string | undefined;
                    'device-uri'?: string | undefined;
                    finishings?: string | undefined;
                    'job-cancel-after'?: number | undefined;
                    'job-hold-until'?: string | undefined;
                    'job-priority'?: number | undefined;
                    'job-sheets'?: string | undefined;
                    'marker-change-time'?: number | undefined;
                    'number-up'?: number | undefined;
                    'printer-commands'?: string | undefined;
                    'printer-info'?: string | undefined;
                    'printer-is-accepting-jobs'?: boolean | undefined;
                    'printer-is-shared'?: boolean | undefined;
                    'printer-is-temporary'?: boolean | undefined;
                    'printer-location'?: string | undefined;
                    'printer-make-and-model'?: string | undefined;
                    'printer-state'?: number | undefined;
                    'printer-state-change-time'?: number | undefined;
                    'printer-state-reasons'?: string | undefined;
                    'printer-type'?: number | undefined;
                    'printer-uri-supported'?: string | undefined;
                    system_driverinfo?: string | undefined;
                } | undefined;
            } | undefined;
        }[];
        lastCheckConnectedPC: Date | number;
        offlineComputers: {
            id?: string | undefined;
            ip: string;
            username?: (string | null) | undefined;
            computerName: string | undefined;
            lastSeen?: (Date | number) | undefined;
            lastPrinted?: (Date | number) | undefined;
            isConnected?: boolean | undefined;
            printers?: {
                name: string;
                displayName: string;
                description: string;
                status: number;
                isDefault: boolean;
                options?: {
                    copies?: string | undefined;
                    'device-uri'?: string | undefined;
                    finishings?: string | undefined;
                    'job-cancel-after'?: number | undefined;
                    'job-hold-until'?: string | undefined;
                    'job-priority'?: number | undefined;
                    'job-sheets'?: string | undefined;
                    'marker-change-time'?: number | undefined;
                    'number-up'?: number | undefined;
                    'printer-commands'?: string | undefined;
                    'printer-info'?: string | undefined;
                    'printer-is-accepting-jobs'?: boolean | undefined;
                    'printer-is-shared'?: boolean | undefined;
                    'printer-is-temporary'?: boolean | undefined;
                    'printer-location'?: string | undefined;
                    'printer-make-and-model'?: string | undefined;
                    'printer-state'?: number | undefined;
                    'printer-state-change-time'?: number | undefined;
                    'printer-state-reasons'?: string | undefined;
                    'printer-type'?: number | undefined;
                    'printer-uri-supported'?: string | undefined;
                    system_driverinfo?: string | undefined;
                } | undefined;
            }[] | undefined;
            printersDefault?: {
                name: string;
                displayName: string;
                description: string;
                status: number;
                isDefault: boolean;
                options?: {
                    copies?: string | undefined;
                    'device-uri'?: string | undefined;
                    finishings?: string | undefined;
                    'job-cancel-after'?: number | undefined;
                    'job-hold-until'?: string | undefined;
                    'job-priority'?: number | undefined;
                    'job-sheets'?: string | undefined;
                    'marker-change-time'?: number | undefined;
                    'number-up'?: number | undefined;
                    'printer-commands'?: string | undefined;
                    'printer-info'?: string | undefined;
                    'printer-is-accepting-jobs'?: boolean | undefined;
                    'printer-is-shared'?: boolean | undefined;
                    'printer-is-temporary'?: boolean | undefined;
                    'printer-location'?: string | undefined;
                    'printer-make-and-model'?: string | undefined;
                    'printer-state'?: number | undefined;
                    'printer-state-change-time'?: number | undefined;
                    'printer-state-reasons'?: string | undefined;
                    'printer-type'?: number | undefined;
                    'printer-uri-supported'?: string | undefined;
                    system_driverinfo?: string | undefined;
                } | undefined;
            } | undefined;
        }[];
    }>;
    reloadDatabase: () => Promise<void>;
    reloadMain: () => Promise<void>;
    lowdb: import("lowdb/lib").LowSync<import("../declarations/LordStore").lordData>;
    reloadLowDB: () => void;
}, "reloadDatabase" | "reloadMain" | "reloadLowDB">>;
